Use getopts to let the user define values like output filenames

diff --git a/gif2gfy b/gif2gfy
--- a/gif2gfy
+++ b/gif2gfy
@@ -4,8 +4,6 @@
 # behavior of ingoring them
 set -e
 
-IN_FILE="${1}"
-
 # Use a POSIX-friendly way of detecting whether a command is installed
 is_available() {
   command -v "${1}" > /dev/null 2>&1
@@ -16,6 +14,25 @@ get_mimetype() {
 
   file -b --mime-type "${FILE}"
 }
+
+while getopts ":i:o:" opt; do
+  case $opt in
+    i)
+      IN_FILE="${OPTARG}"
+      ;;
+    o)
+      OUT_FILE="${OPTARG}"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG. Aborting" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument. Aborting." >&2
+      exit 1
+      ;;
+  esac
+done
 
 if is_available "ffmpeg"; then
   BACKEND="ffmpeg"
@@ -59,11 +76,13 @@ FFPROBE="ffmpeg-2.4.2-64bit-static/ffprobe"
 PARAMETERS="-loglevel quiet -show_entries stream=width,height -print_format csv"
 VIDEO_DATA="$("${FFPROBE}" "${GFY}" ${PARAMETERS})"
 
-OUT_FILE="output.webm.html"
+if [ -z "${OUT_FILE}" ]; then
+  OUT_FILE="output.webm.html"
+fi
 TITLE="${OUT_FILE}"
 OUT_MIMETYPE="$(get_mimetype "${GFY}")"
 WIDTH="$(echo "${VIDEO_DATA}" | cut -d "," -f2)"
-HEIGHT="$(echo "${VIDEO_DATA}" | cut -d "," -f3)"
+HEIGHT="$(echo "${VIDEO_DATA}"|  cut -d "," -f3)"
 DATA="$(base64 -w 0 "${GFY}")"
 
 cat << HTML > "${OUT_FILE}"
