Add initial test for processing .webms

diff --git a/gif2gfy b/gif2gfy
--- a/gif2gfy
+++ b/gif2gfy
@@ -11,7 +11,7 @@ is_available() {
   command -v "${1}" > /dev/null 2>&1
 }
 
-if ! is_available "ffmpeg"; then
+if ! is_available "avconv"; then
   echo "FFmpeg needs to be installed to continue. Aborting."
   exit 1
 fi
@@ -30,5 +30,16 @@ MIMETYPE="$(file --mime-type ${INPUT})"
 MIMETYPE="${MIMETYPE#* }"
 
 # Use temporary directory with clean-up handler for safe creation of temp files
-TEMP_DIR="$(mktemp -d)"
+TEMP_DIR="$(mktemp -d)" || echo 1
 trap 'rm -rf "${TEMP_DIR}"' EXIT
+
+# Path for FFmpeg output, which will then be further processed
+GFY="${TEMP_DIR}/temp.webm"
+
+# If file is .webm, then simply extract the encoded video losslessly
+if [ "${MIMETYPE}" == "video/webm" ]; then
+  ffmpeg -i "${INPUT}" -loglevel panic -vcodec copy -an "${GFY}"
+else
+  echo "Not a supported filetype. Aborting."
+  exit 1
+fi
