Add check for FFmpeg dependency that will halt the program if it's not available

diff --git a/gif2gfy b/gif2gfy
--- a/gif2gfy
+++ b/gif2gfy
@@ -7,3 +7,8 @@ set -e
 is_available() {
   command -v "${1}" > /dev/null 2>&1
 }
+
+if ! is_available "ffmpeg"; then
+  echo "FFmpeg needs to be installed to continue. Aborting."
+  exit 1
+fi
